theme: jekyll-theme-minimal
title: 'CAT Internal Training'
show_downloads: True
navigation:
  - title: Home
    url: /

  - heading: October 2024
  - title: Intro preprocessing (Jordan Data) (Oct 9,18,23)
    url: data_reduction/01-preproc_htstream
  - title: DASHit Protocol (Oct 30)
    url: protocols/dashit

  - heading: November 2024
  - title: Intro RNA Reference Indexing (Jordan Data) (Nov 22)
    url: data_reduction/02-alignment-indexref
  - title: Intro RNA Alignment (Jordan Data) (Nov 22)
    url: data_reduction/02-alignment
  - title: Getting RNA Counts (Jordan Data)
    url: data_reduction/03-counts

  - heading: December 2024
  - title: Intro RNA mapping (Jordan Data) (Nov 22)
    url: data_reduction/01-preproc_htstream

  - heading: Support
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: ETC
  - title: CAT website
    url: https://cat.ucsf.edu/
  - title: Github page
    url: https://github.com/UCSF-CAT-Bioinformatics/CAT_Bioinfo_Training
  - title: Report Errors
    url: https://github.com/UCSF-CAT-Bioinformatics/CAT_Bioinfo_Training/issues
